//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVeXe
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUYENXE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUYENXE()
        {
            this.PHANCONGs = new HashSet<PHANCONG>();
            this.VEs = new HashSet<VE>();
        }
    
        public string MaChuyenXe { get; set; }
        public string MaLichTrinh { get; set; }
        public Nullable<decimal> GiaVe { get; set; }
        public Nullable<System.DateTime> GioChay { get; set; }
        public string MaXe { get; set; }
        public Nullable<int> TinhTrang { get; set; }
    
        public virtual LICHTRINH LICHTRINH { get; set; }
        public virtual XE XE { get; set; }
        public virtual TINHTRANGCHUYENXE TINHTRANGCHUYENXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANCONG> PHANCONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VE> VEs { get; set; }
    }
}
