//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVeXe
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE
    {
        public string MaVe { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public string MaChuyenXe { get; set; }
        public Nullable<int> TinhTrangVe { get; set; }
        public Nullable<int> MaNhanVienBanVe { get; set; }
        public Nullable<int> MaGhe { get; set; }
    
        public virtual CHUYENXE CHUYENXE { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG1 { get; set; }
        public virtual TINHTRANGVE TINHTRANGVE1 { get; set; }
    }
}
